### ISSUE TITLE
Image Encoder Used

### ISSUE THREAD

**Issue by CONSTANT1386** [hqhQAQ/MIP-Adapter#1]
May I ask what kind of clip image encoder the MIP used?

**Comment by hqhQAQ** [comment]
Thanks for the question. The image encoders are adopted following the original IP-Adapter, and they are also downloaded along with [IP-Adapter](https://huggingface.co/h94/IP-Adapter).

Specifically, the image encoder for `sdxl model` is in the `sdxl_models/image_encoder/` folder of IP-Adapter, which is a ViT-G model; The image encoder for `sdxl_plus model` is in the `models/image_encoder/` folder of IP-Adapter, which is a ViT-H model.

**Comment by CONSTANT1386** [comment]
Thank you very much!
