### ISSUE TITLE
GPU resources  for training

### ISSUE THREAD

**Issue by Zlee-wut** [hqhQAQ/MIP-Adapter#2]
Hi! could you share the GPU memory size used for training? Also, what would be the minimum GPU resources required to reproduce the adapter training?

**Comment by hqhQAQ** [comment]
Thanks for the question. We used 8 GPUs with 80GB of memory each for the experiment. Although I haven't conducted this experiment, I believe that 4 or fewer GPUs could achieve the similar performance, albeit with a longer training time.

**Comment by Zlee-wut** [comment]
Thank you!  Regarding the 5 hours of training time on 8 GPUs mentioned in the project description, is this training time based on the Small dataset (10k images) or the original one?

**Comment by Zlee-wut** [comment]
Thank you!  Regarding the 5 hours of training time on 8 GPUs mentioned in the project description, is this training time based on the Small dataset (10k images) or the original one?

**Comment by Zlee-wut** [comment]
Thank you!  Regarding the 5 hours of training time on 8 GPUs mentioned in the project description, is this training time based on the Small dataset (10k images) or the original one?

**Comment by hqhQAQ** [comment]
Actually, the training time is calculated on the Small dataset (10k images).

**Comment by Zlee-wut** [comment]
okay，thank you !
